name: zerospeech-libriabx2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
    - python >=3.8
    - tqdm
    # can't mix n' match pytorch versions btw conda-forge and pytorch channels
    - pytorch::pytorch
    - pytorch::torchaudio
    - pysoundfile
    - numpy
    - pandas
    - pip
    - setuptools >=45
    - setuptools_scm[toml]>=6.2
    - cython
