{% set name = "zerospeech-libriabx2" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zerospeech-libriabx2-{{ version }}.tar.gz
  sha256: 944fd001e5c04cbcf4e2dea5b24701f268610cae55c6ca880b5a5b9f840dbc5e

build:
  skip: true  # [py<38]
  entry_points:
    - zrc-abx2 = zrc_abx2.eval_ABX:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - cython
    - numpy
    - pip
  run:
    - python
    - tqdm
    - pytorch
    - torchaudio
    - pysoundfile
    - pandas
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - zrc_abx2
  commands:
    - pip check
    - zrc-abx2 --help
  requires:
    - pip
    # torchaudio is picky about the distribution of pytorch it uses. In fact,
    # even using the pytorch of the correct version from conda-forge yields a
    # linker error. Let's avoid that in testing here.
    - pytorch::pytorch 1.13.1
    - pytorch::torchaudio 0.13.1

about:
  home: https://pypi.org/project/zerospeech-libriabx2/
  summary: Package implementing a revamped method to the librilight-abx.
  doc_source_url: https://github.com/zerospeech/libri-light-abx2/blob/main/README.md
  license: MIT
  license_file:
    - LICENCE.txt
    - zrc_abx2/cpc/LICENSE
